package Frms;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import ManagementLists.ClientManagement;
import Persons.Clients;
import javax.swing.DefaultListModel;
import java.time.LocalDate;
import ManagementLists.EmployeeManagement;
import Persons.Employees;

/**
 *
 * @author Bella
 */
public class FrmMenu extends javax.swing.JFrame {
 private ClientManagement clientManagement; 
    private DefaultListModel<String> modelClients;  
    private EmployeeManagement employeeManagement; 
private DefaultListModel<String> modelEmployees;
    /**
     * Creates new form NewJFrame
     */
    public FrmMenu() {
        initComponents();
         clientManagement = new ClientManagement();
        modelClients = new DefaultListModel<>();
        JListclients.setModel(modelClients);
        
         employeeManagement = new EmployeeManagement();
    modelEmployees = new DefaultListModel<>();
    Listemployees.setModel(modelEmployees);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabGlobal = new javax.swing.JTabbedPane();
        JPClients = new javax.swing.JPanel();
        txtIDClients = new javax.swing.JTextField();
        txtNameCients = new javax.swing.JTextField();
        txtBirthDateClients = new javax.swing.JTextField();
        txtPhoneClients = new javax.swing.JTextField();
        txtemailClients = new javax.swing.JTextField();
        txtLicenseCLients = new javax.swing.JTextField();
        btnBuscarClients = new javax.swing.JButton();
        txtIdBuscarCLients = new javax.swing.JTextField();
        btnaddCLients = new javax.swing.JButton();
        jListClients = new javax.swing.JScrollPane();
        JListclients = new javax.swing.JList<>();
        JPemployeers = new javax.swing.JPanel();
        txtidEmployee = new javax.swing.JTextField();
        txtNameEmployye = new javax.swing.JTextField();
        txtBirtDateEmployee = new javax.swing.JTextField();
        txtPhoneEmployee = new javax.swing.JTextField();
        txtEmailEmployee = new javax.swing.JTextField();
        txtpositionEmployee = new javax.swing.JTextField();
        txtSalaryEmployee = new javax.swing.JTextField();
        btnBuscarEmployee = new javax.swing.JButton();
        txtidBuscarEmployee = new javax.swing.JTextField();
        btnaddEmployee = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Listemployees = new javax.swing.JList<>();
        JPresevers = new javax.swing.JPanel();
        JPrents = new javax.swing.JPanel();
        JPVehicles = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JLISTvehicles = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabGlobal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, null, null));
        TabGlobal.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        txtIDClients.setText("AQUI VA CEDULA");
        txtIDClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDClientsActionPerformed(evt);
            }
        });

        txtNameCients.setText("AQUI VA EL NOMBRE");

        txtBirthDateClients.setText("FECHA DE NACIMIENTO");
        txtBirthDateClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthDateClientsActionPerformed(evt);
            }
        });

        txtPhoneClients.setText("AQUI VA TELEFONO");

        txtemailClients.setText("AQUI VA CORREO");

        txtLicenseCLients.setText("AQUI VA LICENCIA DE CONDUCIR");

        btnBuscarClients.setText("USADO PARA BUSCAR");

        txtIdBuscarCLients.setText("SE INGRESA CEDULA PARA BUSCAR A LA PERSONA");
        txtIdBuscarCLients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBuscarCLientsActionPerformed(evt);
            }
        });

        btnaddCLients.setText("SE USA PARA AGREGAR CLIENTE");
        btnaddCLients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddCLientsActionPerformed(evt);
            }
        });

        JListclients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListClients.setViewportView(JListclients);

        javax.swing.GroupLayout JPClientsLayout = new javax.swing.GroupLayout(JPClients);
        JPClients.setLayout(JPClientsLayout);
        JPClientsLayout.setHorizontalGroup(
            JPClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPhoneClients)
                        .addComponent(txtNameCients)
                        .addComponent(txtIDClients)
                        .addComponent(txtBirthDateClients)
                        .addComponent(txtemailClients)
                        .addComponent(txtLicenseCLients, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                    .addComponent(btnaddCLients))
                .addGap(18, 18, 18)
                .addGroup(JPClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdBuscarCLients, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(btnBuscarClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jListClients))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        JPClientsLayout.setVerticalGroup(
            JPClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPClientsLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(JPClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPClientsLayout.createSequentialGroup()
                        .addComponent(txtIDClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNameCients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBirthDateClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemailClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicenseCLients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jListClients))
                .addGap(59, 59, 59)
                .addGroup(JPClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPClientsLayout.createSequentialGroup()
                        .addComponent(btnBuscarClients)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdBuscarCLients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnaddCLients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        TabGlobal.addTab("Clients", JPClients);

        txtidEmployee.setText("SE AGREGA CEDULA");
        txtidEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidEmployeeActionPerformed(evt);
            }
        });

        txtNameEmployye.setText("SE AGREGA MOMBRE");

        txtBirtDateEmployee.setText("SE AGREGA FECHA DE NACIMIENTO");

        txtPhoneEmployee.setText("SE AGREGA TELEFONO");

        txtEmailEmployee.setText("SE AGREGA CORREO");
        txtEmailEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEmployeeActionPerformed(evt);
            }
        });

        txtpositionEmployee.setText("SE AGREGA PUESTO");

        txtSalaryEmployee.setText("SE AGREGA SALARIO");

        btnBuscarEmployee.setText("BOTON PARA BUSCAR");
        btnBuscarEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBuscarEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmployeeActionPerformed(evt);
            }
        });

        txtidBuscarEmployee.setText("SE INGRESA CEDULA PARA BUSCAR");

        btnaddEmployee.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnaddEmployee.setText("BOTON SE USA PARA AGREGAR EMPLEADO");
        btnaddEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnaddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddEmployeeActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(Listemployees);

        javax.swing.GroupLayout JPemployeersLayout = new javax.swing.GroupLayout(JPemployeers);
        JPemployeers.setLayout(JPemployeersLayout);
        JPemployeersLayout.setHorizontalGroup(
            JPemployeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPemployeersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPemployeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPemployeersLayout.createSequentialGroup()
                        .addComponent(btnBuscarEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidBuscarEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPemployeersLayout.createSequentialGroup()
                        .addGroup(JPemployeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnaddEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtidEmployee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameEmployye, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBirtDateEmployee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneEmployee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailEmployee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpositionEmployee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalaryEmployee, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        JPemployeersLayout.setVerticalGroup(
            JPemployeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPemployeersLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(JPemployeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPemployeersLayout.createSequentialGroup()
                        .addComponent(txtidEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNameEmployye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBirtDateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpositionEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalaryEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddEmployee))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(JPemployeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEmployee)
                    .addComponent(txtidBuscarEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        TabGlobal.addTab("Employees", JPemployeers);

        javax.swing.GroupLayout JPreseversLayout = new javax.swing.GroupLayout(JPresevers);
        JPresevers.setLayout(JPreseversLayout);
        JPreseversLayout.setHorizontalGroup(
            JPreseversLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        JPreseversLayout.setVerticalGroup(
            JPreseversLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        TabGlobal.addTab("Resevers", JPresevers);

        javax.swing.GroupLayout JPrentsLayout = new javax.swing.GroupLayout(JPrents);
        JPrents.setLayout(JPrentsLayout);
        JPrentsLayout.setHorizontalGroup(
            JPrentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        JPrentsLayout.setVerticalGroup(
            JPrentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        TabGlobal.addTab("Rents", JPrents);

        jTextField9.setText("SE INGRESA PLACA");

        jTextField10.setText("SE INGRESA MARCA");

        jTextField11.setText("SE INGRESA MODELO");

        jTextField12.setText("SE INGRESA AÑO");

        jTextField13.setText("SE INGRESA TIPO");

        jTextField14.setText("SE INGRESA ESTADO");

        jTextField15.setText("SE INGRESA PLACA PARA BUSCAR");

        jButton3.setText("BOTON PARA BUSCAR");

        JLISTvehicles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(JLISTvehicles);

        javax.swing.GroupLayout JPVehiclesLayout = new javax.swing.GroupLayout(JPVehicles);
        JPVehicles.setLayout(JPVehiclesLayout);
        JPVehiclesLayout.setHorizontalGroup(
            JPVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPVehiclesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPVehiclesLayout.createSequentialGroup()
                        .addGroup(JPVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(jTextField10)
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextField12)
                            .addComponent(jTextField13)
                            .addComponent(jTextField14))
                        .addGap(247, 247, 247)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        JPVehiclesLayout.setVerticalGroup(
            JPVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPVehiclesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPVehiclesLayout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addGap(69, 69, 69)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        TabGlobal.addTab("Vehicles", JPVehicles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabGlobal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabGlobal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDClientsActionPerformed

    private void txtBirthDateClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthDateClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthDateClientsActionPerformed

    private void txtIdBuscarCLientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBuscarCLientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBuscarCLientsActionPerformed

    private void txtEmailEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEmployeeActionPerformed

    private void btnaddCLientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddCLientsActionPerformed
try {
        // Leer valores de los txt
        int id = Integer.parseInt(txtIDClients.getText().trim());
        String nombre = txtNameCients.getText().trim();
        String telefono = txtPhoneClients.getText().trim();
        String email = txtemailClients.getText().trim();
        String licencia = txtLicenseCLients.getText().trim();
        LocalDate nacimiento = LocalDate.parse(txtBirthDateClients.getText().trim()); // formato yyyy-MM-dd

        // Crear cliente
        Clients nuevo = new Clients(licencia, id, nombre, telefono, email, nacimiento);

        // Agregarlo con clientManagement
        if (clientManagement.add(nuevo)) {
            modelClients.addElement(nuevo.getId() + " - " + nuevo.getName() + " (Edad: " + nuevo.getAge() + ")");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un cliente con esa cédula.");
        }

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddCLientsActionPerformed

    private void txtidEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidEmployeeActionPerformed

    private void btnaddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddEmployeeActionPerformed
        // TODO add your handling code here:
        
      try {
        // Leer valores de los txt
        int id = Integer.parseInt(txtidEmployee.getText().trim());
        String nombre = txtNameEmployye.getText().trim();
        String telefono = txtPhoneEmployee.getText().trim();
        String email = txtEmailEmployee.getText().trim();
        String puesto = txtpositionEmployee.getText().trim();
        double salario = Double.parseDouble(txtSalaryEmployee.getText().trim());
        LocalDate nacimiento = LocalDate.parse(txtBirtDateEmployee.getText().trim()); // yyyy-MM-dd

        // Crear empleado
        Employees nuevo = new Employees(puesto, salario, id, nombre, telefono, email, nacimiento);

        // Agregarlo con employeeManagement
        if (employeeManagement.add(nuevo)) {
            modelEmployees.addElement(
                nuevo.getId() + " - " + nuevo.getName() +
                " | Puesto: " + nuevo.getPosition() +
                " | Salario: " + nuevo.getSalary() + "₡"
            );
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un empleado con esa cédula.");
        }

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
  
    }//GEN-LAST:event_btnaddEmployeeActionPerformed

    private void btnBuscarEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmployeeActionPerformed
        // TODO add your handling code here:
        
         try {
        int id = Integer.parseInt(txtidBuscarEmployee.getText().trim());
        
        Employees encontrado = employeeManagement.search(id);
        
        if (encontrado != null) {
            // Abrir el formulario FrmFindEmployee y pasarle el empleado encontrado
            FrmFindEmployee frm = new FrmFindEmployee(encontrado, employeeManagement, modelEmployees);
            frm.setVisible(true);
        } else {
            throw new Exception("No se encontró ningún empleado con esa cédula.");
        }
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un número válido de cédula.");
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
        
    }//GEN-LAST:event_btnBuscarEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JLISTvehicles;
    private javax.swing.JList<String> JListclients;
    private javax.swing.JPanel JPClients;
    private javax.swing.JPanel JPVehicles;
    private javax.swing.JPanel JPemployeers;
    private javax.swing.JPanel JPrents;
    private javax.swing.JPanel JPresevers;
    private javax.swing.JList<String> Listemployees;
    private javax.swing.JTabbedPane TabGlobal;
    private javax.swing.JButton btnBuscarClients;
    private javax.swing.JButton btnBuscarEmployee;
    private javax.swing.JButton btnaddCLients;
    private javax.swing.JButton btnaddEmployee;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jListClients;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtBirtDateEmployee;
    private javax.swing.JTextField txtBirthDateClients;
    private javax.swing.JTextField txtEmailEmployee;
    private javax.swing.JTextField txtIDClients;
    private javax.swing.JTextField txtIdBuscarCLients;
    private javax.swing.JTextField txtLicenseCLients;
    private javax.swing.JTextField txtNameCients;
    private javax.swing.JTextField txtNameEmployye;
    private javax.swing.JTextField txtPhoneClients;
    private javax.swing.JTextField txtPhoneEmployee;
    private javax.swing.JTextField txtSalaryEmployee;
    private javax.swing.JTextField txtemailClients;
    private javax.swing.JTextField txtidBuscarEmployee;
    private javax.swing.JTextField txtidEmployee;
    private javax.swing.JTextField txtpositionEmployee;
    // End of variables declaration//GEN-END:variables
}
